import { ArticleCard } from '@/components/blog/ArticleCard';
import { Button } from '@/components/ui/button';
import { posts } from '@/lib/data';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import Link from 'next/link';
import type { Post } from '@/types';

export default function Home() {
  const categories = ['All', ...Array.from(new Set(posts.map(p => p.category)))];
  const featuredPost = posts[0];
  const recentPosts = posts.slice(1, 7);

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Hero Section */}
      <section className="mb-16 text-center">
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl md:text-6xl font-headline">
          Welcome to Hagaaty AI Blog
        </h1>
        <p className="mt-4 max-w-2xl mx-auto text-lg text-muted-foreground sm:text-xl">
          Discover cutting-edge articles generated by AI, and interact with our smart assistant for any questions.
        </p>
        <div className="mt-8 flex justify-center gap-4">
          <Button asChild size="lg">
            <Link href="#recent-posts">Explore Articles</Link>
          </Button>
          <Button asChild size="lg" variant="outline">
            <Link href="/dashboard/generate">Generate an Article</Link>
          </Button>
        </div>
      </section>

      {/* Featured Post */}
      {featuredPost && (
        <section className="mb-16">
           <h2 className="text-3xl font-bold tracking-tight mb-8 font-headline">Featured Post</h2>
          <ArticleCard post={featuredPost} isFeatured />
        </section>
      )}


      {/* Recent Posts */}
      <section id="recent-posts">
        <h2 className="text-3xl font-bold tracking-tight mb-8 font-headline">Recent Posts</h2>
        <Tabs defaultValue="All" className="w-full">
          <TabsList className="grid w-full grid-cols-3 md:w-auto md:grid-flow-col">
            {categories.map(category => (
              <TabsTrigger key={category} value={category}>{category}</TabsTrigger>
            ))}
          </TabsList>
          {categories.map(category => (
            <TabsContent key={category} value={category}>
              <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                {(category === 'All' ? recentPosts : recentPosts.filter(p => p.category === category)).map(post => (
                  <ArticleCard key={post.id} post={post} />
                ))}
              </div>
            </TabsContent>
          ))}
        </Tabs>
      </section>
    </div>
  );
}
